language: python
sudo: required
services:
- docker
python:
- '3.6'
install:
- pip install -r requirements.dev.txt
- pip install --upgrade .
script:
- pycodestyle --show-source src
- mypy src --ignore-missing-imports
- pytest
notifications:
  email: false
